exclude: ^(\.vscode/.+)$
repos:
- repo: https://github.com/hugoh/pre-commit-fish
  rev: v1.2
  hooks:
  - id: fish_syntax
  - id: fish_indent
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.39.0
  hooks:
  - id: markdownlint
    args: [--fix, --disable=MD041]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=50]
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-symlinks
  - id: check-toml
  - id: debug-statements
  - id: destroyed-symlinks
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - id: mixed-line-ending
  - id: no-commit-to-branch
    args: [--branch, stable]
  - id: trailing-whitespace
- repo: https://github.com/pycqa/flake8
  rev: '7.0.0'
  hooks:
  - id: flake8
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.2.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
- repo: local
  hooks:
  - id: bump-version
    name: Bump version
    entry: bump-version.fish
    language: script
    stages: [commit-msg]
ci:
  autofix_commit_msg: 'style: modified by hook'
  autoupdate_commit_msg: 'ci: pre-commit autoupdate'
  skip:
  - fish_indent
  - fish_syntax
  - no-commit-to-branch
  - bump-version
