name: Release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: fish-shop/install-fish-shell@v2
    - name: Install jq
      run: |
        sudo apt install jq
    - name: Create changelog
      run: ops/create-changelog.fish -s > CHANGELOG.md
    - name: Create SBOM
      run: |
        pip-audit --format cyclonedx-json --output sbom.json --progress-spinner off .
    - uses: softprops/action-gh-release@v2.5.0
      with:
        body_path: CHANGELOG.md
        files: sbom.json
